### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ruiruian** [YuWang24/MultiTune#1]
Hi, 

when I use this code for 3D images，I replace the 2D operator with 3D，but i get an error:

Exception has occurred: AttributeError
'builtin_function_or_method' object has no attribute 'view'
  File "G:\code\python\MultiTune\segment_model.py", line 69, in forward
    action_mask = action.float.view()(-1, 1, 1, 1, 1)
  File "G:\code\python\MultiTune\main.py", line 65, in train
    outputs = net.forward(images, policy)
  File "G:\code\python\MultiTune\main.py", line 208, in <module>
    agent_optimizer)

Hope your help

**Comment by YuWang24** [comment]
The error indicates that the action.float() has no attribute called "view". Try to print "action" and have a look at what it is. And please double check whether you're using exactly the same environments.

**Comment by ruiruian** [comment]
@YuWang24  Thank you!

However, I have another issue, I trained net and agent, and loss  normally drops, but when I tested on train set data,  the result was bad,  do you know the reason?  Is it a training issue?

Hope your help, thank you.
